# Generated by Django 3.2 on 2021-09-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ex',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_total', models.CharField(max_length=20)),
                ('user_percent', models.CharField(max_length=20)),
                ('user_division', models.CharField(max_length=20)),
            ],
        ),
    ]
